### ISSUE TITLE
Issue /w Projekte Ablehnen -> Speichern

### ISSUE THREAD

**Issue by leanderpeter** [leanderpeter/university_project_selector#9]
Wenn man ein Projekt anlegt, es daraufhin ablehnt, dann bearbeitet und im Form auf Speichern drueckt erhaelt man folgende Fehlermeldung:

![error](https://user-images.githubusercontent.com/65714982/104810338-22a7ef80-57f4-11eb-96da-7faa7fd1a5bd.png)

**Comment by JannikMerz** [comment]
Bei mir kommt da kein error
